// src/utils/audioMap.js
// AUTO-GENERATED by scripts/generate_audio.js — do not edit by hand.
// Run `npm run generate-audio` to regenerate.

export const audioMap = {
  "Let's turn fractions into decimals, all the way from tenths to hundredths!": "assets/audio/audio_lets_turn_fractions_into_decimals_all_the_way_from_tent_0.mp3",
  "Hmm, I wonder! If Ethan has sold 7 out of 10 slices of a pizza, how would you write that amount as a decimal?": "assets/audio/audio_hmm_i_wonder_if_ethan_has_sold_7_out_of_10_slices_of_a__1.mp3",
  "Fractions and decimals can describe the exact same amount!": "assets/audio/audio_fractions_and_decimals_can_describe_the_exact_same_amou_2.mp3",
  "Hmm, I wonder! Why does 0.06 mean something completely different from 0.6, even though they use the same digits?": "assets/audio/audio_hmm_i_wonder_why_does_006_mean_something_completely_dif_3.mp3",
  "Where a digit sits after the decimal point changes its value!": "assets/audio/audio_where_a_digit_sits_after_the_decimal_point_changes_its__4.mp3",
  "Hmm, I wonder! If a mosaic has 100 tiles and 23 are painted gold, what decimal describes the gold tiles?": "assets/audio/audio_hmm_i_wonder_if_a_mosaic_has_100_tiles_and_23_are_paint_5.mp3",
  "A 10×10 grid is a perfect picture of hundredths!": "assets/audio/audio_a_1010_grid_is_a_perfect_picture_of_hundredths_6.mp3",
  "Hmm, I wonder! Who finished faster: a runner who took 0.6 of a lap, or one who took 0.45 of a lap?": "assets/audio/audio_hmm_i_wonder_who_finished_faster_a_runner_who_took_06_o_7.mp3",
  "Comparing decimals is just like comparing fractions!": "assets/audio/audio_comparing_decimals_is_just_like_comparing_fractions_8.mp3",
  "Hmm, I wonder! Is there a quick way to tell that 1/2, 5/10, and 0.5 are all exactly the same amount?": "assets/audio/audio_hmm_i_wonder_is_there_a_quick_way_to_tell_that_12_510_a_9.mp3",
  "Fractions and decimals are just two ways of writing the same number!": "assets/audio/audio_fractions_and_decimals_are_just_two_ways_of_writing_the_10.mp3",
  "Ethan is running the pizza stall at the school fun fair. Each pizza is cut into 10 equal slices, and he's sold 7 of them. The digital order screen only accepts decimal numbers, not fractions. \"7 out of 10 slices... how do I write that as a decimal?\" he wonders.": "assets/audio/audio_ethan_is_running_the_pizza_stall_at_the_school_fun_fair_11.mp3",
  "Mia grins. \"Easy! 7 out of 10 slices is the fraction 7/10. And 7/10 is exactly the same amount as the decimal 0.7 — seven tenths! Whenever the bottom number is 10, it just slides into the first spot after the decimal point.\"": "assets/audio/audio_mia_grins_easy_7_out_of_10_slices_is_the_fraction_710_a_12.mp3",
  "Tally the Owl swoops down. \"Every fraction over 10 becomes tenths in a decimal! And if you cut into 100 equal pieces instead, each tiny piece is one hundredth — written 0.01. So 23 out of 100 pieces is 0.23!\"": "assets/audio/audio_tally_the_owl_swoops_down_every_fraction_over_10_become_13.mp3",
  "Ethan types 0.7 into the screen — order logged! By the end of the fair, he's converting every fraction to a decimal in his head. \"Fractions and decimals are just two ways to write the exact same amount!\"": "assets/audio/audio_ethan_types_07_into_the_screen_order_logged_by_the_end__14.mp3",
  "Station one — Grid Shader! Tap to shade squares and build a fraction. Once you're done shading, tell us the matching decimal. Let's go!": "assets/audio/audio_station_one_grid_shader_tap_to_shade_squares_and_build__15.mp3",
  "Station two — Flip the Decimal! Look at the known fraction and its decimal. Find the missing number to complete its flipped or equivalent form. Look carefully!": "assets/audio/audio_station_two_flip_the_decimal_look_at_the_known_fraction_16.mp3",
  "Final station — Decimal Sentence! You will see a fraction-decimal sentence with one blank. Think of the matching value first, then use the number pad to fill it in. You've got this!": "assets/audio/audio_final_station_decimal_sentence_you_will_see_a_fractiond_17.mp3",
  "The Boss Battle begins! Answer the questions correctly to defeat the boss and claim your Decimal Master trophy!": "assets/audio/audio_the_boss_battle_begins_answer_the_questions_correctly_t_18.mp3",
  "You defeated the boss! The Golden Decimal Trophy is yours!": "assets/audio/audio_you_defeated_the_boss_the_golden_decimal_trophy_is_your_19.mp3",
  "Let's see how far you've come on your decimals journey!": "assets/audio/audio_lets_see_how_far_youve_come_on_your_decimals_journey_20.mp3",
};
